
---
#removal of docker and repo on CENTOS
- hosts: i7
  become: true
  tasks:
    - name: uninstalling docker repo
      yum_repository:
        name: docker_ce-repo
        description: repo Docker-ce
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: no
        gpgcheck: no

#installing docker latest
    - name: docker newest installation
      yum:
        name: docker
        state: absent
