---
#nstallation of prerequisite for Debian type machines 
- name: docker install part1-DEBIAN
  hosts: debian 
  become: true
#task 
  tasks:
  - name: install Docker Pre REQ
    apt:
      name: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: present 
