---

  - name: install role  K8 master
    import_tasks: k8_master_install.yml
  - name: install role k8 nodes
    import_taks: K8_install.yml


  - name: Docker CE install prerequisite 
  - import_tasks: docker_pre-req_yum.yml
  - name: Docker install
  - import_tasks: docker_install_yum.yml

